[package]
name = "newton-metrics"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
repository.workspace = true
description = "prometheus server for metrics"
license-file.workspace = true

# docs.rs-specific configuration
# see https://docs.rs/about/metadata
[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[dependencies]

metrics.workspace = true
metrics-exporter-prometheus.workspace = true
metrics-util = "0.19.0"
tracing.workspace = true

[dev-dependencies]
# We don't use workspace due to:
# https://github.com/rust-lang/cargo/issues/4242#issuecomment-2578428685
newton-testing-utils = { path = "../../tests/testing-utils" }
newton-metrics-collectors-rpc-calls = { path = "./collectors/rpc_calls" }
newton-metrics-collectors-economic = { path = "./collectors/economic" }
newton-client-elcontracts = { path = "../chainio/clients/elcontracts" }
newton-client-avsregistry = { path = "../chainio/clients/avsregistry" }

alloy.workspace = true
num-bigint.workspace = true
reqwest = "0.12.4"
tokio.workspace = true
