[package]
name = "newton-testing-utils"
publish = false
description = "Testing utils for eigen."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license-file.workspace = true
repository.workspace = true

# docs.rs-specific configuration
# see https://docs.rs/about/metadata
[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[lints]
workspace = true

[dependencies]
alloy.workspace = true
newton-client-avsregistry.workspace = true
newton-client-elcontracts.workspace = true
newton-common.workspace = true
newton-utils.workspace = true
newton-crypto-bls.workspace = true
serde.workspace = true
serde_json.workspace = true
testcontainers.workspace = true
url.workspace = true
