[package]
name = "examples-avsregistry-write"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
repository.workspace = true
license-file.workspace = true
authors.workspace = true
description = "avsregistry write examples"

[lints]
workspace = true

[dependencies]
alloy.workspace = true
ark-bn254 = "0.4.0"
ark-ec = { version = "0.4.2", default-features = false }
ark-ff.workspace = true
ark-serialize = "0.4"
ark-std = { version = "0.4.0", default-features = false }
newton-client-avsregistry.workspace = true
newton-client-elcontracts.workspace = true
newton-crypto-bls.workspace = true
newton-crypto-bn254.workspace = true

newton-testing-utils.workspace = true
newton-types.workspace = true
newton-utils.workspace = true
newton-common.workspace = true
eyre.workspace = true
lazy_static = "1.5.0"
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
