[package]
name = "examples-avsregistry-read"
publish = false
version.workspace = true
edition.workspace = true
rust-version.workspace = true
repository.workspace = true
license-file.workspace = true
authors.workspace = true
description = "avsregistry read examples"

[lints]
workspace = true

[dependencies]
alloy.workspace = true
newton-client-avsregistry.workspace = true

newton-testing-utils.workspace = true
eyre.workspace = true
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
