[package]
name = "newton-client-multichain"
description = "Eigen Layer Multichain Client"

version.workspace = true
edition.workspace = true
rust-version.workspace = true
repository.workspace = true
license-file.workspace = true

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[dependencies]
alloy.workspace = true
async-trait.workspace = true
newton-types.workspace = true
newton-crypto-bls.workspace = true
newton-crypto-bn254.workspace = true
newton-crypto-ecdsa.workspace = true
newton-common.workspace = true
newton-utils.workspace = true
thiserror.workspace = true
tracing.workspace = true

[lints]
workspace = true
