[package]
name = "newton-services-multichain"
description = "Eigen Layer Multichain Services"

version.workspace = true
edition.workspace = true
rust-version.workspace = true
repository.workspace = true
license-file.workspace = true

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[dependencies]
alloy.workspace = true
ark-ec.workspace = true
ark-ff.workspace = true
async-trait.workspace = true
newton-common.workspace = true
newton-types.workspace = true
newton-crypto-bls.workspace = true
newton-crypto-bn254.workspace = true
newton-crypto-ecdsa.workspace = true
newton-client-multichain.workspace = true
newton-services-blsaggregation.workspace = true
newton-utils.workspace = true
futures = "0.3"
rs_merkle = "1.5.0"
thiserror.workspace = true
tokio.workspace = true
tracing.workspace = true

[lints]
workspace = true
