#![allow(unused_imports, clippy::all, rustdoc::all)]
//! This module contains the sol! generated bindings for solidity contracts.
//! This is autogenerated code.
//! Do not manually edit these files.
//! These files may be overwritten by the codegen system at any time.
pub mod r#bn254_certificate_verifier;
pub mod r#cross_chain_registry;
pub mod r#ecdsa_certificate_verifier;
pub mod r#i_base_certificate_verifier;
pub mod r#i_cross_chain_registry;
pub mod r#i_operator_table_calculator;
pub mod r#i_operator_table_updater;
pub mod r#ibn254_certificate_verifier;
pub mod r#iecdsa_certificate_verifier;
pub mod r#operator_table_updater;
