[package]
name = "newton-eigensdk"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
repository.workspace = true
description = "SDK for eigenlayer"
license-file.workspace = true

# docs.rs-specific configuration
# see https://docs.rs/about/metadata
[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[dependencies]
newton-client-avsregistry = { workspace = true, optional = true }
newton-client-elcontracts = { workspace = true, optional = true }
newton-client-eth = { workspace = true, optional = true }
newton-client-fireblocks = { workspace = true, optional = true }
newton-crypto-bls = { workspace = true, optional = true }
newton-crypto-bn254 = { workspace = true, optional = true }
newton-metrics = { workspace = true, optional = true }
newton-metrics-collectors-economic = { workspace = true, optional = true }
newton-metrics-collectors-rpc-calls = { workspace = true, optional = true }
newton-services-avsregistry = { workspace = true, optional = true }
newton-services-blsaggregation = { workspace = true, optional = true }
newton-services-operatorsinfo = { workspace = true, optional = true }
newton-signer = { workspace = true, optional = true }
newton-testing-utils = { workspace = true, optional = true }
newton-types = { workspace = true, optional = true }
newton-utils = { workspace = true, optional = true }
newton-nodeapi = { workspace = true, optional = true }
newton-common = { workspace = true, optional = true }

# Feature configurations
[features]
default = []


# Full features set for full usage
full = [
    "client-avsregistry",
    "client-elcontracts",
    "client-eth",
    "client-fireblocks",
    "common",
    "crypto-bls",
    "crypto-bn254",
    "metrics",
    "services-avsregistry",
    "services-blsaggregation",
    "services-operatorsinfo",
    "signer",
    "testing-utils",
    "nodeapi",
    "metrics-collectors-economic",
    "metrics-collectors-rpc-calls",
    "types",
    "utils",
]

# Client-related features
client-avsregistry = ["dep:newton-client-avsregistry"]
client-elcontracts = ["dep:newton-client-elcontracts"]
client-eth = ["dep:newton-client-eth"]
client-fireblocks = ["dep:newton-client-fireblocks"]


# Crypto-related features
crypto-bls = ["dep:newton-crypto-bls"]
crypto-bn254 = ["dep:newton-crypto-bn254"]

# Metrics and collectors
metrics = ["dep:newton-metrics"]
metrics-collectors-economic = ["dep:newton-metrics-collectors-economic"]
metrics-collectors-rpc-calls = ["dep:newton-metrics-collectors-rpc-calls"]

# Service-related features
services-avsregistry = ["dep:newton-services-avsregistry"]
services-blsaggregation = ["dep:newton-services-blsaggregation"]
services-operatorsinfo = ["dep:newton-services-operatorsinfo"]

# Node API related features
nodeapi = ["dep:newton-nodeapi"]

# Utilities
utils = ["dep:newton-utils"]

# Testing utilities
testing-utils = ["dep:newton-testing-utils"]

# Signer-related features
signer = ["dep:newton-signer"]

# types
types = ["dep:newton-types"]

#common utilities
common = ["dep:newton-common"]
