[package]
name = "info-operator-service"
publish = false
description = "Example demonstrating the operatorsinfo crate"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
repository.workspace = true
license-file.workspace = true

[dependencies]
alloy.workspace = true

newton-common.workspace = true
newton-client-avsregistry.workspace = true
newton-client-elcontracts.workspace = true
newton-crypto-bls.workspace = true
newton-testing-utils.workspace = true
newton-services-operatorsinfo.workspace = true
newton-utils.workspace = true
tokio = { workspace = true, features = ["full"] }
tracing.workspace = true
tokio-util = "0.7.11"
